// Code generated by "stringer -type edge"; DO NOT EDIT.

package unused

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[edgeAlias-1]
	_ = x[edgeBlankField-2]
	_ = x[edgeAnonymousStruct-4]
	_ = x[edgeCgoExported-8]
	_ = x[edgeConstGroup-16]
	_ = x[edgeElementType-32]
	_ = x[edgeEmbeddedInterface-64]
	_ = x[edgeExportedConstant-128]
	_ = x[edgeExportedField-256]
	_ = x[edgeExportedFunction-512]
	_ = x[edgeExportedMethod-1024]
	_ = x[edgeExportedType-2048]
	_ = x[edgeExportedVariable-4096]
	_ = x[edgeExtendsExportedFields-8192]
	_ = x[edgeExtendsExportedMethodSet-16384]
	_ = x[edgeFieldAccess-32768]
	_ = x[edgeFunctionArgument-65536]
	_ = x[edgeFunctionResult-131072]
	_ = x[edgeFunctionSignature-262144]
	_ = x[edgeImplements-524288]
	_ = x[edgeInstructionOperand-1048576]
	_ = x[edgeInterfaceCall-2097152]
	_ = x[edgeInterfaceMethod-4194304]
	_ = x[edgeKeyType-8388608]
	_ = x[edgeLinkname-16777216]
	_ = x[edgeMainFunction-33554432]
	_ = x[edgeNamedType-67108864]
	_ = x[edgeNetRPCRegister-134217728]
	_ = x[edgeNoCopySentinel-268435456]
	_ = x[edgeProvidesMethod-536870912]
	_ = x[edgeReceiver-1073741824]
	_ = x[edgeRuntimeFunction-2147483648]
	_ = x[edgeSameObject-4294967296]
	_ = x[edgeSignature-8589934592]
	_ = x[edgeStructConversion-17179869184]
	_ = x[edgeTestSink-34359738368]
	_ = x[edgeTupleElement-68719476736]
	_ = x[edgeType-137438953472]
	_ = x[edgeTypeName-274877906944]
	_ = x[edgeUnderlyingType-549755813888]
	_ = x[edgePointerType-1099511627776]
	_ = x[edgeUnsafeConversion-2199023255552]
	_ = x[edgeUsedConstant-4398046511104]
	_ = x[edgeVarDecl-8796093022208]
}

const _edge_name = "edgeAliasedgeBlankFieldedgeAnonymousStructedgeCgoExportededgeConstGroupedgeElementTypeedgeEmbeddedInterfaceedgeExportedConstantedgeExportedFieldedgeExportedFunctionedgeExportedMethodedgeExportedTypeedgeExportedVariableedgeExtendsExportedFieldsedgeExtendsExportedMethodSetedgeFieldAccessedgeFunctionArgumentedgeFunctionResultedgeFunctionSignatureedgeImplementsedgeInstructionOperandedgeInterfaceCalledgeInterfaceMethodedgeKeyTypeedgeLinknameedgeMainFunctionedgeNamedTypeedgeNetRPCRegisteredgeNoCopySentineledgeProvidesMethodedgeReceiveredgeRuntimeFunctionedgeSameObjectedgeSignatureedgeStructConversionedgeTestSinkedgeTupleElementedgeTypeedgeTypeNameedgeUnderlyingTypeedgePointerTypeedgeUnsafeConversionedgeUsedConstantedgeVarDecl"

var _edge_map = map[edge]string{
	1:             _edge_name[0:9],
	2:             _edge_name[9:23],
	4:             _edge_name[23:42],
	8:             _edge_name[42:57],
	16:            _edge_name[57:71],
	32:            _edge_name[71:86],
	64:            _edge_name[86:107],
	128:           _edge_name[107:127],
	256:           _edge_name[127:144],
	512:           _edge_name[144:164],
	1024:          _edge_name[164:182],
	2048:          _edge_name[182:198],
	4096:          _edge_name[198:218],
	8192:          _edge_name[218:243],
	16384:         _edge_name[243:271],
	32768:         _edge_name[271:286],
	65536:         _edge_name[286:306],
	131072:        _edge_name[306:324],
	262144:        _edge_name[324:345],
	524288:        _edge_name[345:359],
	1048576:       _edge_name[359:381],
	2097152:       _edge_name[381:398],
	4194304:       _edge_name[398:417],
	8388608:       _edge_name[417:428],
	16777216:      _edge_name[428:440],
	33554432:      _edge_name[440:456],
	67108864:      _edge_name[456:469],
	134217728:     _edge_name[469:487],
	268435456:     _edge_name[487:505],
	536870912:     _edge_name[505:523],
	1073741824:    _edge_name[523:535],
	2147483648:    _edge_name[535:554],
	4294967296:    _edge_name[554:568],
	8589934592:    _edge_name[568:581],
	17179869184:   _edge_name[581:601],
	34359738368:   _edge_name[601:613],
	68719476736:   _edge_name[613:629],
	137438953472:  _edge_name[629:637],
	274877906944:  _edge_name[637:649],
	549755813888:  _edge_name[649:667],
	1099511627776: _edge_name[667:682],
	2199023255552: _edge_name[682:702],
	4398046511104: _edge_name[702:718],
	8796093022208: _edge_name[718:729],
}

func (i edge) String() string {
	if str, ok := _edge_map[i]; ok {
		return str
	}
	return "edge(" + strconv.FormatInt(int64(i), 10) + ")"
}
